config/routes.rb
Rails.application.routes.draw do
  resources :boardgame_categories
  root 'boardgames#index'
  resources :categories
  resources :user_boardgames
  resources :user_reviews
  resources :boardgames
  resources :users

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to:  'sessions#destroy'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  put 'user_reviews/:id/like', to: 'user_reviews#like', as: 'like'
  get '/highest_rated', to: 'user_reviews#highest_rated', as: 'highest_rated'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_many :user_reviews, dependent: :destroy
    has_many :user_boardgames, dependent: :destroy
    has_many :boardgames, through: :user_boardgames

    validates :username, presence: true, uniqueness: true
    validates :email, presence: true, uniqueness: true
    validates :password, presence: true

    has_secure_password



    def full_name
        "#{self.first_name} #{self.last_name}"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy] 
    skip_before_action :require_login, only: [:new, :create]

    def show
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_boardgame_path(current_user)
        else
            flash[:errors] = @user.errors.full_messages
            redirect_to new_user_path
        end
    end

    def edit
    end

    def update
        @user.update(user_params)
        if @user.save 
            redirect_to user_path(@user)
        else
            flash[:errors] = @user.errors.full_messages
            redirect_to new_user_path
        end
    end


    def destroy
        session[:user_id] = nil
        @user.destroy
        redirect_to new_user_path
    end

    private

    def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :username, :password, :password_confirmation)
    end
        
    def set_user
        @user = User.find(session[:user_id])
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

  <div class="field">
    <%= f.label :username, class: "label" %>
    <%= f.text_field :username, class: "input" %>
  </div>

  <div class="field">
    <%= f.label :password, class: "label" %>
    <%= f.password_field :password, class: "input" %>
  </div>

  <div class="field">
    <%= f.label "Confirm Password", class: "label" %>
    <%= f.password_field :password_confirmation, class: "input" %>
  </div>

  <div class="field">
    <%= f.label :first_name, class: "label" %>
    <%= f.text_field :first_name, class: "input" %>
  </div>

  <div class="field">
    <%= f.label :last_name, class: "label" %>
    <%= f.text_field :last_name, class: "input" %>
  </div>

  <div class="field">
    <%= f.label :email, class: "label" %>
    <%= f.email_field :email, class: "input" %>
  </div>

  <div class="actions">
    <%= f.submit class: "button is-success is-rounded" %>
  </div>

<% end %>

app/views/users/edit.html.erb
<div class="columns is-centered mt-2">
  <div class="column is-one-third">
    <div class="box">
      <h1 class="is-size-2 has-text-weight-bold has-text-centered mb-3"> Edit User</h1>
    </div>
    <%= render 'form' %>
  </div>
</div>

app/views/users/new.html.erb
<div class="columns is-centered mt-2">
  <div class="column is-one-third">
    <div class="box">
      <div class="box has-text-centered is-fullwidth has-background-info-dark">
        <div class="box">
          <h1 class="is-size-2 has-text-weight-bold mb-3"> Sign Up</h1>
        </div>
      </div>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="columns is-centered mt-6">
  <div class="column is-half">
    <div class="box is-fullwidth has-background-info-dark">
      <article class="box">
        <h1 class="subtitle has-text-centered has-text-weight-bold is-size-2"><%= current_user.full_name %>'s Profile</h1>
        <br>
        <p>Username: <%= current_user.username%>
        <br>
          Email: <%= current_user.email%>
        </p>
        <br>
        <br>
        <br>
        <nav class="level">
          <div class="level-item has-text-centered">
            <div>
              <p class="heading">Your Boardgame</p>
              <p class="title button"><%= link_to "Collection", user_boardgame_path(current_user) %></p>
            </div>
          </div>
          <div class="level-item has-text-centered">
            <div>
              <p class="heading">Your</p>
              <p class="title button"><%= link_to "Reviews", user_review_path(current_user) %></p>
            </div>
          </div>
        </nav>
        <br>
        <div class="box has-background-link">
          <div class="box has-text-centered">
            <h4 class="subtitle has-text-primary-dark">Checkout More Games in Categories You Like!</h4>
            <% current_user.boardgames.each do |c| %>
              <% c.categories.each do |u| %>
                <div class="button is-rounded has-background-success-light">
                  <%= link_to u.name, category_path(u) %>
                </div>
                <br>
              <% end %>
            <% end %>
          </div>
        </div>
        <br>
        <div class="action">
          <%= button_to "Edit User", edit_user_path(current_user), method: "get", class: "button is-rounded has-background-link-dark has-text-white"%>
        </div>
        <div class="action">
          <%= button_to "Delete User", user_path(current_user), method: "delete",  data: {confirm: "Are you sure?"}, class: "button is-rounded has-background-danger-dark has-text-white" %>
        </div>
        <div class="action">
          <%= button_to "Back to Search", '/', method: 'get', class: "button is-rounded has-background-success-dark has-text-white" %>
        </div>
      </div>
    </div>
  </div>
</div>