config/routes.rb
Rails.application.routes.draw do
  resources :boardgame_categories
  root 'boardgames#index'
  resources :categories
  resources :user_boardgames
  resources :user_reviews
  resources :boardgames
  resources :users

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to:  'sessions#destroy'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  put 'user_reviews/:id/like', to: 'user_reviews#like', as: 'like'
  get '/highest_rated', to: 'user_reviews#highest_rated', as: 'highest_rated'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :boardgame_categories
    has_many :boardgames, through: :boardgame_categories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
skip_before_action :require_login, only: [:show, :create]

  def show
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.find(params[:category][:id])
    redirect_to category_path(@category)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/show.html.erb
<div class="columns is-centered mt-6">
  <div class="column is-half">
      <div class="box is-fullwidth has-background-info-dark">
        <article class="box">
          <div class="title has-text-centered">
           <b>Browse Category: <br> <%= @category.name %></b>
           <br>
           <br>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<% if @category.boardgames.count == 0 %>
  <p class="subtitle is-danger">Sorry, currently no games in this category.</p>
  <div class="action">
    <br>
    <%= button_to "Back to Search", '/', method: 'get', class:  "button has-background-primary-light"%>
  </div>

  <% else %>

  <div class="action ">
    <br>
    <%= button_to "Back to Search", '/', method: 'get', class:  "button has-background-primary-light"%>
  </div>
<% end %>

<div class="grid">
  <% @category.boardgames.each do |boardgame| %>
    <div class="square">
      <div class="custom-box">
        <div class="table">
          <div class="table-cell">
            <% if boardgame.small_image %>
              <%= link_to (image_tag boardgame.small_image, alt: "boardgame"), boardgame_path(boardgame) %>
              <br>
            <% end %>
            <%= link_to boardgame.name, boardgame_path(boardgame) %>
            <br>
            Players: <%= boardgame.min_players %> - <%= boardgame.max_players %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>