config/routes.rb
Rails.application.routes.draw do
  resources :boardgame_categories
  root 'boardgames#index'
  resources :categories
  resources :user_boardgames
  resources :user_reviews
  resources :boardgames
  resources :users

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to:  'sessions#destroy'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  put 'user_reviews/:id/like', to: 'user_reviews#like', as: 'like'
  get '/highest_rated', to: 'user_reviews#highest_rated', as: 'highest_rated'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/boardgame.rb
class Boardgame < ApplicationRecord
  has_many :boardgame_categories
  has_many :categories, through: :boardgame_categories
  has_many :user_reviews
  has_many :user_boardgames
  has_many :users, through: :user_boardgames

  validates :name, :description, :min_players, :max_players, :year_published, :publisher, presence: :true

  def self.search(search)
    if search
      boardgame = Boardgame.find_by(name: search.titlecase)
      if boardgame

        Boardgame.where('name LIKE ?', '%' + search + '%') #+
      # Boardgame.where("name LIKE ?", "%" + search.first(3) + "%").limit(10)
      else
        Boardgame.where('name LIKE ?', '%' + search.first(3) + '%').limit(10)
      end
    end
  end

  def avg_rating
    if user_reviews.count > 0
      sum = 0
      count = 0
      user_reviews.each do |user_review|
        unless user_review.rating.nil?
          sum += user_review.rating
          count += 1
        end
      end
      sum / count
    end
  end
end

app/controllers/boardgames_controller.rb
class BoardgamesController < ApplicationController
    skip_before_action :require_login, only: [:home, :show, :index, :create]
    # validates :name, :description, :min_players, :max_players, :year_published, :publisher, presence: :true
    # validates :description, length: {minimum: 100}
    # validates :min_players, length: {minimum: 1}

    def index
        @boardgames = Boardgame.all.sample(6)
        if params[:name] != ""
            @boardgame = Boardgame.search(params[:name])
        end
        @cat = Boardgame.search(params[:category_id])
        @category = Category.new
        @categories = Category.all
    end

    def show
        @boardgame = Boardgame.find(params[:id])
    end

    def new
        @boardgame = Boardgame.new
        @categories = Category.all

    end

    def create
        boardgame = Boardgame.create(boardgame_params)
        category = Category.find(params[:boardgame][:id])
        BoardgameCategory.create(:boardgame_id => boardgame.id, category_id: category.id)
        if  boardgame.save
            redirect_to boardgame_path(boardgame)
        else 
            flash[:errors] = boardgame.errors.full_messages
            redirect_to "/"
        end
    end

    private

    def boardgame_params
        params.require(:boardgame).permit(:name, :description, :min_players, :max_players, :year_published, :image_url, :publisher, :thumb_image, :small_image, :medium_image)
    end
end

app/helpers/boardgames_helper.rb
module BoardgamesHelper
end

app/views/boardgames/create.html.erb
<h1>create</h1>
<%= @boardgame.name %>

app/views/boardgames/index.html.erb
<div class="columns is-centered mt-6">
  <div class="column is-half">
      <div class="box is-fullwidth has-background-info-dark has-text-centered">
        <article class="box">
          <h1 class="title">Welcome to your Social Boardgame Experience</h1>
        </article>
      </div>
    </div>
  </div>
</div>

<% if @boardgame %>
  <div class="box">
    <% @boardgame.each do |b| %>
      <div class="search-box">
        <div class="game-name"><%= link_to b.name, boardgame_path(b) %>
          <br>
          <br>
        </div>
        <% if b.small_image %>
          <%= link_to (image_tag b.small_image, alt: "boardgame"), boardgame_path(b) %><br>
        <% end %>
        <% if !b.categories.empty? %>
          <b>Category:</b><% b.categories.each do |e| %>
            <% if b.categories.count > 1 %>
              |
            <% end %>
            <%= link_to e.name, category_path(e) %>
          <% end %>
        <% end %>
        <br>
        <%== b.description.first(300) ...%>
        <%  %>
      </div>
    <% end %>
  <% end %>
</div>

<div class="columns is-centered mt-6">
  <div class="column is-one-third">
    <div class="box is-fullwidth has-background-info-dark">
      <article class="box">
        <%= form_tag boardgames_path, :method => "get" do %>
          <div class="field has-text-centered">
            <%= label_tag :name, "Search Boardgames", class: "label  has-text-centered has-text-danger-dark"%>
            <%= text_field_tag :name, "", class: "input" %>
          </div>
          <div class="action">
            <%= submit_tag "Search", name: nil, class: "button is-rounded is-small is-fullwidth has-background-primary-light" %>
          <% end %>
        </div>
      </article>

      <article class="box">
        <%= form_for @category do |f| %>
        <div class="field has-text-centered">
          <%= f.label "Browse by Category", class: "label has-text-danger-dark" %>
          <%= f.collection_select :id, @categories, :id, :name, controls: "dropdown-menu" %>
        </div>
        <div class="action">
          <%= f.submit 'Browse', name: nil, class: "button is-rounded is-small is-fullwidth has-background-primary-light" %>
        <% end %>
        </div>
      </article>
    </div>

    <div class="action has-text-centered">
      <%= link_to "Highest User Rated Games", highest_rated_path, class: "button is-rounded has-background-info-dark has-text-warning" %>
    </div>
  </div>
</div>

<br>
<br>

<div class="box has-background-success-light	">
  <div class="level">
    <p class="level-item has-text-centered has-text-warning has-text-weight-bold">
      Play?
    </p>
    <p class="level-item has-text-centered has-text-danger has-text-weight-bold">
      Cooperative?
    </p>
    <p class="level-item has-text-weight-bold has-text-grey-light is-size-2 has-text-centered ">
      Try These Random Games
    </p>
    <p class="level-item has-text-centered has-text-primary has-text-weight-bold">
      Competative?
    </p>
    <p class="level-item has-text-centered has-text-info has-text-weight-bold">
      Contactless?
    </p>
  </div>
</div>


<div class="tile is-ancestor">
  <div class="tile is-vertical is-8">
    <div class="tile">
      <div class="tile is-parent is-vertical">
        <article class="tile is-child notification is-primary">
          <% if @boardgames[0].small_image %>
            <%= link_to (image_tag @boardgames[0].small_image, alt: "boardgame"), boardgame_path(@boardgames[0]) %>
          <% end %>
          <% if !@boardgames[0].categories.empty? %>
            <li>Category
            <% @boardgames[0].categories.each do |e| %>
              <% if @boardgames[0].categories.count > 1 %>
                |
              <% end %>
              <%= link_to e.name, category_path(e) %>
            <% end %>
          <% end %>
          <p class="title"><%= @boardgames[0].name %></p>
          <p class="subtitle"><%== @boardgames[0].description.first(300)... %></p>
        </article>

        <article class="tile is-child notification is-warning">
          <% if @boardgames[1].small_image %>
            <%= link_to (image_tag @boardgames[1].small_image, alt: "boardgame"), boardgame_path(@boardgames[1]) %>
          <% end %>
          <% if !@boardgames[1].categories.empty? %>
            <li>Category
            <% @boardgames[1].categories.each do |e| %>
              <% if @boardgames[1].categories.count > 1 %>
                |
              <% end %>
              <%= link_to e.name, category_path(e) %>
            <% end %>
          <% end %>
          <p class="title"><%= @boardgames[1].name %></p>
          <p class="subtitle"><%== @boardgames[1].description.first(200)... %></p>
        </article>
      </div>

      <div class="tile is-parent">
        <article class="tile is-child notification is-info">
          <% if @boardgames[2].medium_image %>
            <%= link_to (image_tag @boardgames[2].medium_image, alt: "boardgame"), boardgame_path(@boardgames[2]) %>
          <% end %>
          <% if !@boardgames[2].categories.empty? %>
            <li>Category
            <% @boardgames[2].categories.each do |e| %>
              <% if @boardgames[2].categories.count > 1 %>
                |
              <% end %>
              <%= link_to e.name, category_path(e) %>
            <% end %>
          <% end %>
          <p class="title"><%= @boardgames[2].name %></p>
          <p class="subtitle"><%== @boardgames[2].description.first(500)... %></p>
        </article>
        <figure class="image is-4by3">
          <img src="https://bulma.io/images/placeholders/640x480.png">
        </figure>
      </div>
    </div>

    <div class="tile is-parent">
      <article class="tile is-child notification is-danger">
        <% if @boardgames[4].small_image %>
          <%= link_to (image_tag @boardgames[4].small_image, alt: "boardgame"), boardgame_path(@boardgames[4]) %>
        <% end %>
        <% if !@boardgames[4].categories.empty? %>
          <p>
          <li>Category
          <% @boardgames[4].categories.each do |e| %>
            <% if @boardgames[4].categories.count > 1 %>
              |
            <% end %>
            <%= link_to e.name, category_path(e) %>
          <% end %>
        <% end %>
        </p>
        <p class="title"><%= @boardgames[4].name %></p>
        <p class="subtitle"><%== @boardgames[4].description.first(700)... %></p>
      </article>
    </div>
  </div>

  <div class="tile is-parent">
    <article class="tile is-child notification is-success">
      <div class="content">
        <% if @boardgames[5].medium_image %>
          <%= link_to (image_tag @boardgames[5].medium_image, alt: "boardgame"), boardgame_path(@boardgames[5]) %>
        <% end %>
        <% if !@boardgames[5].categories.empty? %>
          <li>Category
          <% @boardgames[5].categories.each do |e| %>
            <% if @boardgames[5].categories.count > 1 %>
              |
            <% end %>
            <%= link_to e.name, category_path(e) %>
          <% end %>
        <% end %>
        <p class="title"> <%= @boardgames[5].name %></p>
        <p class="subtitle"><%== @boardgames[5].description.first(1000)... %></p>
      </div>
    </article>
  </div>
</div>

<div class="action">
  <%= link_to "Submit a Boardgame", new_boardgame_path, class: "input button is-link is-centered" %>
</div>

app/views/boardgames/new.html.erb
<div class="columns is-centered mt-2">
  <div class="column is-half">
    <div class="box has-background-info-dark">
      <div class="box">
        <h1 class="is-size-2 has-text-weight-bold has-text-centered mb-3">Share your original boardgame</h1>
      </div>
    </div>
  </div>
</div>

<div class="back_img">
  <div class="columns is-centered mt-2">
    <div class="column is-one-third">
      <div class="box has-background-info-dark">
        <div class="box">
            <%= form_for @boardgame do |f| %>
              <div class="field">
                <%= f.label :name, class: "label" %>
                <%= f.text_field :name, class: "input" %>
                <br>
              </div>
              <div class="field">
                <%= f.label :description, class: "label" %>
                <%= f.text_area :description, class: "input" %>
                <br>
              </div>
              <div class="field">
                <%= f.label "Minimum Players", class: "label" %>
                <%= f.number_field :min_players, class: "input" %>
                <br>
              </div>
              <div class="field">
                <%= f.label "Maximum Players", class: "label" %>
                <%= f.number_field :max_players, class: "input" %>
                <br>
              </div>
              <div class="field">
                <%= f.label :year_published, class: "label" %>
                <%= f.number_field :year_published, class: "input" %>
                <br>
              </div>
              <div class="field">
                <%= f.label :image_url, class: "label" %>
                <%= f.text_field :image_url, class: "input" %>
                <br>
              </div>
              <div class="field">
                <%= f.label "Game Inventor", class: "label" %>
                <%= f.text_field :publisher, class: "input" %>
                <br>
              </div>
              <div class="field">
                <%= f.label 'Category', class: "label" %>
                <%= f.collection_select :id, @categories, :id, :name %>
              <br>
              </div>

              <div class="actions">
                <%= f.submit class: "button is-success is-rounded"%>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/boardgames/show.html.erb
<div class="action is-right-aligned">
  <br>
  <%= button_to "Back to Search", '/', method: 'get', class:  "button has-background-primary-light"%>
</div>
<br>
<br>

<div class="show-box">
  <% if @boardgame.medium_image %>
    <%= image_tag @boardgame.medium_image %>
  <% end %>
</div>

<div class="search-box">
  <div class="box">
    <div class="game-name"><%= @boardgame.name %></div>
      <h4>Players: <%= (@boardgame.min_players != 0 ? @boardgame.min_players : 0) %> to <%= @boardgame.max_players %></h4>
      <h4>Year Published: <%= @boardgame.year_published %></h4>
      <% if !@boardgame.categories.empty? %>
        <b>Category:</b> <% @boardgame.categories.each do |c| %>
          <% if @boardgame.categories.count > 1 %>
          |
          <% end %>
        <%= link_to c.name, category_path(c) %>
      <% end %>
    <% end%>
    <br>
    <%== @boardgame.description %>
    <br>
    <br>
    <% if @boardgame.avg_rating != nil %>
      <div class="game-name">
        Average User Rating: <%= @boardgame.avg_rating %>
      </div>
      <br>
    <% end %>

    <% if current_user %>
      <%= form_tag user_boardgames_path do %>
        <%= hidden_field_tag :boardgame_id, @boardgame.id%>
        <div class="action">
          <%= submit_tag "Add Game to User Collection", class: "button is-dark is-rounded" %>
        </div>
      <% end %>
    <% end %>

    <% if !current_user %>
      <%= button_to "Log in to submit a review or add game to collection", login_path, method: "get", class:  "button has-background-primary-light"%>
    <% end %>

    <div class="columns is-left mt-6">
      <div class="column is-half">
        <% @boardgame.user_reviews.each do |r| %>
          <div class="box is-fullwidth">
            <div>
              <p class=""><b> Review:</b> <%= r.review %></p>
            </div>
            <div>
              <p class=""><b>Rating:</b> <%= r.rating %>
            </div>
            <div>
              <p class=""><b>Submitted By:</b> <%= r.user.username %>
            </div>
            <div>
              <%= pluralize(r.thumbs, 'Like') %>
            </div>
            <div class="action">
              <%= button_to "Like", like_path(r), method: :put, class: "button is-rounded has-background-link-light" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <% if current_user %>
    <div class="columns is-left mt-6">
      <div class="column is-half">
        <div class="box is-fullwidth">
          <%= form_tag user_reviews_path do %>
            <div class="field">
              <%= label_tag :review, "Write a Review:", class: "label" %>
              <%= text_area_tag :review, "", class: "input is-half"%>
            </div>
            <div class="field">
              <%= label_tag :rating, "Rating:", class: "label"%>
              <%= number_field_tag :rating, nil, :in => 1..10%>
            </div>
            <div class="action">
              <%= submit_tag "Submit Review", class: "button is-small is-rounded"%>
            </div>
              <%= hidden_field_tag :boardgame_id, @boardgame.id%>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>